<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <!--<caption>Carte du restaurant</caption>-->
    <tbody>
      <main>
        <link rel="stylesheet" href="<?= $wwwUrl ?>/css/home.css">

        <h1>Bienvenue sur Beer4you</h1>

        <p id="home-presentation">Le site de vente de bière le plus côté du marché, ici vous trouverez les  meilleurs bières, de la 86 ) la knonenbourg. Nous mettons un point d'honneur à vous la facturer chère et à vous livrer tiède.</p>


        <img src="<?= $wwwUrl ?>/images/logo/kroHome.jpg" alt="image">
    </main>
    </tbody>
</table>
