  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/profil.css">

<div>
<h3>Mon profil</h3>


<form  class="b-form" action="<?= $requestUrl ?>/user/profil" method="POST">
  <input type="text" name="firstname" placeholder="Prénom" value="<?=$profile['FirstName']?>">
  <input type="text" name="lastname" placeholder="Nom" value="<?=$profile['LastName']?>">
  <input type="text" name="email" placeholder="Email" value="<?=$profile['Email']?>">
  <input type="text" name="address" placeholder="Adresse" value="<?=$profile['Address']?>">s
  <input type="text" name="city" placeholder="Ville" value="<?=$profile['City']?>">
  <input type="text" name="zip" placeholder="CP" value="<?=$profile['Zip']?>">
  <input type=submit value="Modifier">
</form>

</div>

<hr/>

<h4>Récapitulatif des commandes</h4>
<p>Cliquez sur un numéro de commande pour voir le détail !</p>
<table class="t-order">
	<thead>
		<th>Numéro de commande</th>
		<th>Prix total</th>
		<th>Date de la commande</th>
	</thead>
	<tbody>
		<?php foreach ($orders as $order): ?>
			<tr>
				<td class="link"><a href="<?=$requestUrl ?>/user/profil/detail?id=<?=$order['Id']?>"><?=$order['Id']?></a></td>
				<td><?=number_format($order['TotalAmount'], 2)?> €</td>
				<td><?=date('d/m/Y', strtotime($order['CreationTimestamp']))?></td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
